purchase_type: on_demand
subnet_id: subnet-01bc006215b4bfa36
num_instances: 3
key_name: insight-aws2
security_group_ids: sg-04950952b61aa079b 
instance_type: m4.large
tag_name: crystal-project-spark-cluster
vol_size: 100
role: worker
use_eips: true
