purchase_type: on_demand
subnet_id: subnet-01bc006215b4bfa36
num_instances: 1
key_name: insight-aws2
security_group_ids: sg-08d81fc64ffc3f309
instance_type: m4.large
tag_name: crystal-project-database-cluster
vol_size: 100
role: master
use_eips: true
