purchase_type: on_demand
subnet_id: subnet-01bc006215b4bfa36
num_instances: 1
key_name: insight-aws2
security_group_ids: sg-0a0422eec1ff30887
instance_type: m4.4xlarge
tag_name: crystal-project-web-server
vol_size: 100
role: master
use_eips: true
